name: KRNLWorker
options:
  bundleIdPrefix: space.krnlcamel.worker
  deploymentTarget:
    iOS: "16.0"

settings:
  SWIFT_VERSION: "5.9"

targets:
  KRNLWorker:
    type: application
    platform: iOS
    sources:
      - KRNLWorker
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: space.krnlcamel.worker
      INFOPLIST_FILE: KRNLWorker/Info.plist
      TARGETED_DEVICE_FAMILY: "1"